version: '3.5'  
services:  
    customer-ui:  
      container_name: ui
      build: . 
      image: angular
      ports: 
         - '4200:4200'
      command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"